apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" . }}-backend-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  capacity:
    storage: {{ .Values.mysql.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
